template-file-path: labInfrastructure.yaml
parameters:
  S3UserName: s3-user-roland-lab
  EC2UserName: ec2-user-roland-lab
  PasswordLength: '12'
  S3GroupName: S3ReadOnlyGroupRolandLab
  EC2GroupName: EC2ReadOnlyGroupRolandLab
tags: {}
